[project]
name = "agno-asimov"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno==2.5.10",
    "chonkie>=1.6.8",
    "chromadb>=1.5.9",
    "ddgs>=9.12.0",
    "fastapi[standard]>=0.135.3",
    "groq==1.1.2",
    "openai==2.30.0",
    "pypdf>=6.14.2",
    "python-decouple>=3.8",
    "sqlalchemy>=2.0.48",
    "tavily-python==0.7.23",
    "uvicorn>=0.42.0",
    "yfinance==1.2.0",
]
